In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
df = pd.read_csv("heart.csv")
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0


In [2]:
df.isna().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [4]:
label_encoder = {}
for col in df.select_dtypes(include=['object']).columns:
    le = LabelEncoder()
    df[col] = le.fit_transform(df[col])
    label_encoder[col] = le

In [6]:
from sklearn.model_selection import train_test_split
X = df.drop(columns=['target'])
y = df['target']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [7]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
from sklearn.svm import SVC
svm_linear = SVC(kernel='linear', C=1)
svm_linear.fit(X_train, y_train)
y_pred_linear = svm_linear.predict(X_test)

In [9]:
accuracy_linear = (y_test == y_pred_linear).mean()
accuracy_linear

np.float64(0.8146341463414634)

In [15]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_linear)



array([[72, 30],
       [ 8, 95]])

In [12]:
svm_poly = SVC(kernel='poly', degree=3, C=1)
svm_poly.fit(X_train, y_train)
y_pred_poly = svm_poly.predict(X_test)

In [13]:
accuracy_linear = (y_pred_poly == y_test).mean()
accuracy_linear

np.float64(0.9073170731707317)

In [14]:
confusion_matrix (y_test, y_pred_poly)

array([[ 85,  17],
       [  2, 101]])

In [18]:
svm_rbf = SVC(kernel='rbf' , C=1, gamma='scale')
svm_rbf.fit(X_train, y_train)
y_pred_rbf = svm_rbf.predict(X_test)

In [20]:
accuracy_linear = (y_pred_rbf == y_test).mean()
accuracy_linear

np.float64(0.8878048780487805)

In [21]:
confusion_matrix(y_test, y_pred_rbf)

array([[85, 17],
       [ 6, 97]])